# Generated by Django 4.2.3 on 2023-07-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_userprofile_address_userprofile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar',
            new_name='pro_pic',
        ),
    ]
