# Generated by Django 4.2.3 on 2023-07-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_rename_avatar_userprofile_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pro_pic',
            field=models.ImageField(blank=True, upload_to='profileimages/'),
        ),
    ]
