# Generated by Django 4.2.3 on 2023-07-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_alter_userprofile_pro_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pro_pic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
