# Generated by Django 4.2.3 on 2023-07-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_commentry'),
        ('authen', '0006_remove_userprofile_pro_pic_userprofile_avatar'),
    ]

    operations = [
    ]
