# Generated by Django 4.2.3 on 2023-07-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_merge_20230730_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentry',
        ),
    ]
