# Generated by Django 4.2.3 on 2023-08-01 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0008_delete_commentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishtitle', models.CharField(max_length=250, unique=True)),
                ('wish', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_achieved', models.BooleanField(blank=True, default=False)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
