# Generated by Django 4.2.3 on 2023-08-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0009_wish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
