# Generated by Django 4.2.2 on 2023-06-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0004_remove_contact_phone_contact_pnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='pnumber',
            new_name='pnum',
        ),
    ]
