# Generated by Django 4.2.3 on 2023-07-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0006_customer_order_product_digital_shippingaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_slug', models.CharField(max_length=150)),
                ('category_image', models.ImageField(blank=True, default='', null=True, upload_to='shop/images')),
                ('category_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plantapp.category'),
        ),
    ]
