# Generated by Django 4.2.4 on 2023-08-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0004_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wishlist_images/'),
        ),
    ]
