# Generated by Django 4.2.4 on 2023-08-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0005_wishlistitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='image',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='wishproduct',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plantapp.product'),
        ),
    ]
