# Generated by Django 4.2.4 on 2023-08-21 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0006_remove_wishlistitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantapp.customer'),
        ),
    ]
