# Generated by Django 4.2.4 on 2023-08-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0007_remove_wishlistitem_user_wishlistitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='reason',
        ),
    ]
