# Generated by Django 4.2.4 on 2023-08-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0008_remove_wishlistitem_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='status',
        ),
    ]
